### ISSUE TITLE
Lua5.2/Lua5.3 compatibility

### ISSUE THREAD

**Issue by msva** [openresty/lua-rds-parser#5]
```
lua5.2: error loading module 'rds.parser' from file '/usr/lib64/lua/5.2/rds/parser.so':
        /usr/lib64/lua/5.2/rds/parser.so: undefined symbol: luaL_register
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: in ?

lua5.3: error loading module 'rds.parser' from file '/usr/lib64/lua/5.3/rds/parser.so':
        /usr/lib64/lua/5.3/rds/parser.so: undefined symbol: luaL_register
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: in ?

```

Can you consider moving away from `luaL_register` (and global scope loading) and move to new 5.2+ API (local scope) with adding wrapper for 5.1?

**Comment by agentzh** [comment]
@msva This library is created for OpenResty, which only supports the Lua 5.1 ABI anyway.

**Comment by msva** [comment]
Officially, yes :) But anyway, global-exporting is bad practice, as was [stated][ref] in lua-l list. And, by the way, many resty-libs do support Lua5.2/5.3 too, so, despite officially OpenResty is Lua5.1-ABI only, it is possible to use it with 5.2+ :)


[ref]: http://lua.2524044.n2.nabble.com/Why-did-luaL-openlib-luaL-register-go-td7649023.html

**Comment by agentzh** [comment]
Yes, global exporting is bad. We could fix that. This library is no longer of much interest to me since lua-resty-redis obsoletes this. I have no interest in investing our valuable developer time on supporting Lua 5.2, 5.3, ... x.x. OpenResty cannot work with Lua 5.2+ without major redesign BTW.
